name: Python-Anwendung

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Installiere Python und Abh채ngigkeiten
    - name: Python einrichten
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Abh채ngigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest
      # F체hre Pytest aus
    - name: Tests ausf체hren
      run: pytest
