name: Python-Anwendung

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v2

    - name: Python einrichten
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest

    - name: Tests ausführen
      run: |
        pytest tests/test_app.py
